message(STATUS "${CONAN_LIB_DIRS_SQLITE3PP}")

find_path(SQLITE3PP_INCLUDE_DIR NAMES sqlite3pp.h PATHS ${CONAN_INCLUDE_DIRS_SQLITE3PP})
find_library(SQLITE3PP_LIBRARY NAMES ${CONAN_LIBS_SQLITE3PP} PATHS ${CONAN_BUILD_DIRS_SQLITE3PP})

set(SQLITE3PP_INCLUDE_DIRS ${SQLITE3PP_INCLUDE_DIR})
set(SQLITE3PP_LIBRARIES ${SQLITE3PP_LIBRARY})

mark_as_advanced(SQLITE3PP_LIBRARY SQLITE3PP_INCLUDE_DIR)

message("** SQLite3++ found by Conan!")
set(SQLITE3PP_FOUND TRUE)
message("   - includes: ${SQLITE3PP_INCLUDE_DIRS}")
message("   - libraries: ${SQLITE3PP_LIBRARIES}")
